# Generated by Django 5.0.3 on 2024-04-02 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_periodocurso_turma_curso_avaliacao_disciplina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='Disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina', verbose_name='Avaliação da disciplina'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='AreaSaber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areasaber', verbose_name='Area da Pessoa'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='Instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instituicao', verbose_name='Instituição da Pessoa'),
        ),
    ]
