# Generated by Django 5.0.3 on 2024-04-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_avaliacao_disciplina_alter_curso_areasaber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiavaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do tipo de avaliação')),
            ],
            options={
                'verbose_name': 'Tipo de avaliação',
                'verbose_name_plural': 'Tipos de avaliações',
            },
        ),
    ]
