# Generated by Django 5.0.3 on 2024-04-16 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tiavaliacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Nome da descricao')),
                ('data', models.DateField(verbose_name='Data')),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Frequencia do curso')),
                ('Disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina', verbose_name='Frequencia da disciplina')),
                ('Pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Frequencia da pessoa')),
            ],
            options={
                'verbose_name': 'Ocorrencia',
                'verbose_name_plural': 'Ocorrencias',
            },
        ),
    ]
